// Generated by Haxe 3.4.0
(function ($global) { "use strict";
function $extend(from, fields) {
	function Inherit() {} Inherit.prototype = from; var proto = new Inherit();
	for (var name in fields) proto[name] = fields[name];
	if( fields.toString !== Object.prototype.toString ) proto.toString = fields.toString;
	return proto;
}
var EReg = function(r,opt) {
	this.r = new RegExp(r,opt.split("u").join(""));
};
EReg.__name__ = true;
EReg.prototype = {
	match: function(s) {
		if(this.r.global) {
			this.r.lastIndex = 0;
		}
		this.r.m = this.r.exec(s);
		this.r.s = s;
		return this.r.m != null;
	}
	,__class__: EReg
};
Math.__name__ = true;
var Std = function() { };
Std.__name__ = true;
Std.string = function(s) {
	return js_Boot.__string_rec(s,"");
};
var haxe_io_FPHelper = function() { };
haxe_io_FPHelper.__name__ = true;
haxe_io_FPHelper.i32ToFloat = function(i) {
	var sign = 1 - (i >>> 31 << 1);
	var exp = i >>> 23 & 255;
	var sig = i & 8388607;
	if(sig == 0 && exp == 0) {
		return 0.0;
	}
	return sign * (1 + Math.pow(2,-23) * sig) * Math.pow(2,exp - 127);
};
haxe_io_FPHelper.floatToI32 = function(f) {
	if(f == 0) {
		return 0;
	}
	var af = f < 0 ? -f : f;
	var exp = Math.floor(Math.log(af) / 0.6931471805599453);
	if(exp < -127) {
		exp = -127;
	} else if(exp > 128) {
		exp = 128;
	}
	var sig = Math.round((af / Math.pow(2,exp) - 1) * 8388608);
	if(sig == 8388608 && exp < 128) {
		sig = 0;
		++exp;
	}
	return (f < 0 ? -2147483648 : 0) | exp + 127 << 23 | sig;
};
var js__$Boot_HaxeError = function(val) {
	Error.call(this);
	this.val = val;
	this.message = String(val);
	if(Error.captureStackTrace) {
		Error.captureStackTrace(this,js__$Boot_HaxeError);
	}
};
js__$Boot_HaxeError.__name__ = true;
js__$Boot_HaxeError.wrap = function(val) {
	if((val instanceof Error)) {
		return val;
	} else {
		return new js__$Boot_HaxeError(val);
	}
};
js__$Boot_HaxeError.__super__ = Error;
js__$Boot_HaxeError.prototype = $extend(Error.prototype,{
	__class__: js__$Boot_HaxeError
});
var js_Boot = function() { };
js_Boot.__name__ = true;
js_Boot.getClass = function(o) {
	if((o instanceof Array) && o.__enum__ == null) {
		return Array;
	} else {
		var cl = o.__class__;
		if(cl != null) {
			return cl;
		}
		var name = js_Boot.__nativeClassName(o);
		if(name != null) {
			return js_Boot.__resolveNativeClass(name);
		}
		return null;
	}
};
js_Boot.__string_rec = function(o,s) {
	if(o == null) {
		return "null";
	}
	if(s.length >= 5) {
		return "<...>";
	}
	var t = typeof(o);
	if(t == "function" && (o.__name__ || o.__ename__)) {
		t = "object";
	}
	switch(t) {
	case "function":
		return "<function>";
	case "object":
		if(o instanceof Array) {
			if(o.__enum__) {
				if(o.length == 2) {
					return o[0];
				}
				var str = o[0] + "(";
				s += "\t";
				var _g1 = 2;
				var _g = o.length;
				while(_g1 < _g) {
					var i = _g1++;
					if(i != 2) {
						str += "," + js_Boot.__string_rec(o[i],s);
					} else {
						str += js_Boot.__string_rec(o[i],s);
					}
				}
				return str + ")";
			}
			var l = o.length;
			var i1;
			var str1 = "[";
			s += "\t";
			var _g11 = 0;
			var _g2 = l;
			while(_g11 < _g2) {
				var i2 = _g11++;
				str1 += (i2 > 0 ? "," : "") + js_Boot.__string_rec(o[i2],s);
			}
			str1 += "]";
			return str1;
		}
		var tostr;
		try {
			tostr = o.toString;
		} catch( e ) {
			return "???";
		}
		if(tostr != null && tostr != Object.toString && typeof(tostr) == "function") {
			var s2 = o.toString();
			if(s2 != "[object Object]") {
				return s2;
			}
		}
		var k = null;
		var str2 = "{\n";
		s += "\t";
		var hasp = o.hasOwnProperty != null;
		for( var k in o ) {
		if(hasp && !o.hasOwnProperty(k)) {
			continue;
		}
		if(k == "prototype" || k == "__class__" || k == "__super__" || k == "__interfaces__" || k == "__properties__") {
			continue;
		}
		if(str2.length != 2) {
			str2 += ", \n";
		}
		str2 += s + k + " : " + js_Boot.__string_rec(o[k],s);
		}
		s = s.substring(1);
		str2 += "\n" + s + "}";
		return str2;
	case "string":
		return o;
	default:
		return String(o);
	}
};
js_Boot.__interfLoop = function(cc,cl) {
	if(cc == null) {
		return false;
	}
	if(cc == cl) {
		return true;
	}
	var intf = cc.__interfaces__;
	if(intf != null) {
		var _g1 = 0;
		var _g = intf.length;
		while(_g1 < _g) {
			var i = _g1++;
			var i1 = intf[i];
			if(i1 == cl || js_Boot.__interfLoop(i1,cl)) {
				return true;
			}
		}
	}
	return js_Boot.__interfLoop(cc.__super__,cl);
};
js_Boot.__instanceof = function(o,cl) {
	if(cl == null) {
		return false;
	}
	switch(cl) {
	case Array:
		if((o instanceof Array)) {
			return o.__enum__ == null;
		} else {
			return false;
		}
		break;
	case Bool:
		return typeof(o) == "boolean";
	case Dynamic:
		return true;
	case Float:
		return typeof(o) == "number";
	case Int:
		if(typeof(o) == "number") {
			return (o|0) === o;
		} else {
			return false;
		}
		break;
	case String:
		return typeof(o) == "string";
	default:
		if(o != null) {
			if(typeof(cl) == "function") {
				if(o instanceof cl) {
					return true;
				}
				if(js_Boot.__interfLoop(js_Boot.getClass(o),cl)) {
					return true;
				}
			} else if(typeof(cl) == "object" && js_Boot.__isNativeObj(cl)) {
				if(o instanceof cl) {
					return true;
				}
			}
		} else {
			return false;
		}
		if(cl == Class ? o.__name__ != null : false) {
			return true;
		}
		if(cl == Enum ? o.__ename__ != null : false) {
			return true;
		}
		return o.__enum__ == cl;
	}
};
js_Boot.__nativeClassName = function(o) {
	var name = js_Boot.__toStr.call(o).slice(8,-1);
	if(name == "Object" || name == "Function" || name == "Math" || name == "JSON") {
		return null;
	}
	return name;
};
js_Boot.__isNativeObj = function(o) {
	return js_Boot.__nativeClassName(o) != null;
};
js_Boot.__resolveNativeClass = function(name) {
	return $global[name];
};
var js_html_compat_ArrayBuffer = function(a) {
	if((a instanceof Array) && a.__enum__ == null) {
		this.a = a;
		this.byteLength = a.length;
	} else {
		var len = a;
		this.a = [];
		var _g1 = 0;
		var _g = len;
		while(_g1 < _g) {
			var i = _g1++;
			this.a[i] = 0;
		}
		this.byteLength = len;
	}
};
js_html_compat_ArrayBuffer.__name__ = true;
js_html_compat_ArrayBuffer.sliceImpl = function(begin,end) {
	var u = new Uint8Array(this,begin,end == null ? null : end - begin);
	var result = new ArrayBuffer(u.byteLength);
	var resultArray = new Uint8Array(result);
	resultArray.set(u);
	return result;
};
js_html_compat_ArrayBuffer.prototype = {
	slice: function(begin,end) {
		return new js_html_compat_ArrayBuffer(this.a.slice(begin,end));
	}
	,__class__: js_html_compat_ArrayBuffer
};
var js_html_compat_Float32Array = function() { };
js_html_compat_Float32Array.__name__ = true;
js_html_compat_Float32Array._new = function(arg1,offset,length) {
	var arr;
	if(typeof(arg1) == "number") {
		arr = [];
		var _g1 = 0;
		var _g = arg1;
		while(_g1 < _g) {
			var i = _g1++;
			arr[i] = 0;
		}
		arr.byteLength = arr.length << 2;
		arr.byteOffset = 0;
		var _g2 = [];
		var _g21 = 0;
		var _g11 = arr.length << 2;
		while(_g21 < _g11) {
			var i1 = _g21++;
			_g2.push(0);
		}
		arr.buffer = new js_html_compat_ArrayBuffer(_g2);
	} else if(js_Boot.__instanceof(arg1,js_html_compat_ArrayBuffer)) {
		var buffer = arg1;
		if(offset == null) {
			offset = 0;
		}
		if(length == null) {
			length = buffer.byteLength - offset >> 2;
		}
		arr = [];
		var _g12 = 0;
		var _g3 = length;
		while(_g12 < _g3) {
			var i2 = _g12++;
			var val = buffer.a[offset++] | buffer.a[offset++] << 8 | buffer.a[offset++] << 16 | buffer.a[offset++] << 24;
			arr.push(haxe_io_FPHelper.i32ToFloat(val));
		}
		arr.byteLength = arr.length << 2;
		arr.byteOffset = offset;
		arr.buffer = buffer;
	} else if((arg1 instanceof Array) && arg1.__enum__ == null) {
		arr = arg1.slice();
		var buffer1 = [];
		var _g4 = 0;
		while(_g4 < arr.length) {
			var f = arr[_g4];
			++_g4;
			var i3 = haxe_io_FPHelper.floatToI32(f);
			buffer1.push(i3 & 255);
			buffer1.push(i3 >> 8 & 255);
			buffer1.push(i3 >> 16 & 255);
			buffer1.push(i3 >>> 24);
		}
		arr.byteLength = arr.length << 2;
		arr.byteOffset = 0;
		arr.buffer = new js_html_compat_ArrayBuffer(buffer1);
	} else {
		throw new js__$Boot_HaxeError("TODO " + Std.string(arg1));
	}
	arr.subarray = js_html_compat_Float32Array._subarray;
	arr.set = js_html_compat_Float32Array._set;
	return arr;
};
js_html_compat_Float32Array._set = function(arg,offset) {
	if(js_Boot.__instanceof(arg.buffer,js_html_compat_ArrayBuffer)) {
		var a = arg;
		if(arg.byteLength + offset > this.byteLength) {
			throw new js__$Boot_HaxeError("set() outside of range");
		}
		var _g1 = 0;
		var _g = arg.byteLength;
		while(_g1 < _g) {
			var i = _g1++;
			this[i + offset] = a[i];
		}
	} else if((arg instanceof Array) && arg.__enum__ == null) {
		var a1 = arg;
		if(a1.length + offset > this.byteLength) {
			throw new js__$Boot_HaxeError("set() outside of range");
		}
		var _g11 = 0;
		var _g2 = a1.length;
		while(_g11 < _g2) {
			var i1 = _g11++;
			this[i1 + offset] = a1[i1];
		}
	} else {
		throw new js__$Boot_HaxeError("TODO");
	}
};
js_html_compat_Float32Array._subarray = function(start,end) {
	var a = js_html_compat_Float32Array._new(this.slice(start,end));
	a.byteOffset = start * 4;
	return a;
};
var js_html_compat_Uint8Array = function() { };
js_html_compat_Uint8Array.__name__ = true;
js_html_compat_Uint8Array._new = function(arg1,offset,length) {
	var arr;
	if(typeof(arg1) == "number") {
		arr = [];
		var _g1 = 0;
		var _g = arg1;
		while(_g1 < _g) {
			var i = _g1++;
			arr[i] = 0;
		}
		arr.byteLength = arr.length;
		arr.byteOffset = 0;
		arr.buffer = new js_html_compat_ArrayBuffer(arr);
	} else if(js_Boot.__instanceof(arg1,js_html_compat_ArrayBuffer)) {
		var buffer = arg1;
		if(offset == null) {
			offset = 0;
		}
		if(length == null) {
			length = buffer.byteLength - offset;
		}
		if(offset == 0) {
			arr = buffer.a;
		} else {
			arr = buffer.a.slice(offset,offset + length);
		}
		arr.byteLength = arr.length;
		arr.byteOffset = offset;
		arr.buffer = buffer;
	} else if((arg1 instanceof Array) && arg1.__enum__ == null) {
		arr = arg1.slice();
		arr.byteLength = arr.length;
		arr.byteOffset = 0;
		arr.buffer = new js_html_compat_ArrayBuffer(arr);
	} else {
		throw new js__$Boot_HaxeError("TODO " + Std.string(arg1));
	}
	arr.subarray = js_html_compat_Uint8Array._subarray;
	arr.set = js_html_compat_Uint8Array._set;
	return arr;
};
js_html_compat_Uint8Array._set = function(arg,offset) {
	if(js_Boot.__instanceof(arg.buffer,js_html_compat_ArrayBuffer)) {
		var a = arg;
		if(arg.byteLength + offset > this.byteLength) {
			throw new js__$Boot_HaxeError("set() outside of range");
		}
		var _g1 = 0;
		var _g = arg.byteLength;
		while(_g1 < _g) {
			var i = _g1++;
			this[i + offset] = a[i];
		}
	} else if((arg instanceof Array) && arg.__enum__ == null) {
		var a1 = arg;
		if(a1.length + offset > this.byteLength) {
			throw new js__$Boot_HaxeError("set() outside of range");
		}
		var _g11 = 0;
		var _g2 = a1.length;
		while(_g11 < _g2) {
			var i1 = _g11++;
			this[i1 + offset] = a1[i1];
		}
	} else {
		throw new js__$Boot_HaxeError("TODO");
	}
};
js_html_compat_Uint8Array._subarray = function(start,end) {
	var a = js_html_compat_Uint8Array._new(this.slice(start,end));
	a.byteOffset = start;
	return a;
};
var om_App = function() { };
om_App.__name__ = true;
var om_System = function() { };
om_System.__name__ = true;
om_System.isMobile = function(userAgent,mobileUserAgents) {
	if(userAgent == null) {
		userAgent = window.navigator.userAgent;
	}
	if(mobileUserAgents == null) {
		mobileUserAgents = om_System.mobileUserAgents;
	}
	return new EReg(mobileUserAgents.join("|"),"i").match(userAgent);
};
var om_audio_VolumeMeter = function(audio,bufferSize,clipLevel,averaging,clipLag) {
	if(clipLag == null) {
		clipLag = 750;
	}
	if(averaging == null) {
		averaging = 0.95;
	}
	if(clipLevel == null) {
		clipLevel = 0.98;
	}
	if(bufferSize == null) {
		bufferSize = 512;
	}
	var _gthis = this;
	this.clipLevel = clipLevel;
	this.averaging = averaging;
	this.clipLag = clipLag;
	var clipping = false;
	var lastClip = 0.0;
	this.processor = audio.createScriptProcessor(bufferSize);
	this.processor.checkClipping = function() {
		if(!clipping) {
			return false;
		}
		if(lastClip + clipLag < window.performance.now()) {
			clipping = false;
		}
		return clipping;
	};
	var buf;
	var sum = 0.0;
	var x;
	this.processor.onaudioprocess = function(e) {
		buf = e.inputBuffer.getChannelData(0);
		sum = 0.0;
		var _g1 = 0;
		var _g = buf.length;
		while(_g1 < _g) {
			var i = _g1++;
			x = buf[i];
			if((x < 0 ? -x : x) >= clipLevel) {
				clipping = true;
				lastClip = window.performance.now();
			}
			sum += x * x;
		}
		_gthis.rms = Math.sqrt(sum / buf.length);
		var a = _gthis.rms;
		var b = _gthis.volume * averaging;
		_gthis.volume = a < b ? b : a;
		_gthis.decibel = 10 * (Math.log(_gthis.volume) / 2.302585092994046);
	};
	this.processor.connect(audio.destination);
};
om_audio_VolumeMeter.__name__ = true;
om_audio_VolumeMeter.prototype = {
	__class__: om_audio_VolumeMeter
};
var soda_App = function() { };
soda_App.__name__ = true;
soda_App.__interfaces__ = [om_App];
soda_App.update = function(time) {
	window.requestAnimationFrame(soda_App.update);
	soda_App.frequencyAnalyser.getByteFrequencyData(soda_App.frequencyData);
	soda_App.waveformAnalyser.getFloatTimeDomainData(soda_App.waveformData);
	soda_App.spectrum.draw(soda_App.frequencyData,soda_App.waveformData);
	soda_App.info.textContent = (soda_App.meter.decibel | 0) + "";
};
soda_App.handleKeyDown = function(e) {
};
soda_App.handleWindowResize = function(e) {
	soda_App.spectrum.resize(window.innerWidth,window.innerHeight);
};
soda_App.fatalError = function(info) {
	window.console.error(info);
	window.document.body.innerHTML = "";
	var e = window.document.createElement("div");
	e.id = "fatal-error";
	e.textContent = info;
};
soda_App.init = function() {
	navigator.mediaDevices.getUserMedia({ audio : true}).then(function(stream) {
		soda_App.audio = new AudioContext();
		soda_App.frequencyAnalyser = soda_App.audio.createAnalyser();
		soda_App.frequencyAnalyser.fftSize = 256;
		soda_App.waveformAnalyser = soda_App.audio.createAnalyser();
		soda_App.waveformAnalyser.fftSize = 2048;
		soda_App.waveformAnalyser.connect(soda_App.frequencyAnalyser);
		soda_App.frequencyData = new Uint8Array(soda_App.frequencyAnalyser.frequencyBinCount);
		soda_App.waveformData = new Float32Array(soda_App.waveformAnalyser.frequencyBinCount);
		soda_App.microphone = soda_App.audio.createMediaStreamSource(stream);
		soda_App.microphone.connect(soda_App.waveformAnalyser);
		soda_App.meter = new om_audio_VolumeMeter(soda_App.audio);
		soda_App.microphone.connect(soda_App.meter.processor);
		window.addEventListener("resize",soda_App.handleWindowResize,false);
		window.addEventListener("keydown",soda_App.handleKeyDown,false);
		window.requestAnimationFrame(soda_App.update);
	})["catch"](function(e) {
		var info = e.name;
		if(e.message.length > 0) {
			info += ": " + Std.string(e.message);
		}
		soda_App.fatalError(info);
	});
};
soda_App.main = function() {
	window.onload = function() {
		window.document.body.innerHTML = "";
		window.document.addEventListener("contextmenu",function(e) {
			e.preventDefault();
		});
		soda_App.isMobile = om_System.isMobile();
		soda_App.spectrum = new soda_Spectrum();
		window.document.body.appendChild(soda_App.spectrum.element);
		soda_App.info = window.document.createElement("div");
		soda_App.info.classList.add("info");
		soda_App.info.textContent = "SODA";
		window.document.body.appendChild(soda_App.info);
		if(soda_App.isMobile) {
			window.document.body.addEventListener("touchstart",function(e1) {
				window.document.body.removeEventListener("touchstart",soda_App.init);
				window.document.documentElement.webkitRequestFullscreen();
				soda_App.init();
			},false);
		} else {
			soda_App.init();
		}
	};
};
var soda_Spectrum = function() {
	this.element = window.document.createElement("div");
	this.element.classList.add("spectrum");
	this.grid = window.document.createElement("canvas");
	this.grid.classList.add("grid");
	this.grid.width = window.innerWidth;
	this.grid.height = window.innerHeight;
	this.element.appendChild(this.grid);
	this.canvas = window.document.createElement("canvas");
	this.canvas.classList.add("spectrum");
	this.canvas.width = window.innerWidth;
	this.canvas.height = window.innerHeight;
	this.element.appendChild(this.canvas);
	this.ctx = this.canvas.getContext("2d",null);
	this.drawGrid(36);
	this.frequencyHistory = [];
};
soda_Spectrum.__name__ = true;
soda_Spectrum.prototype = {
	resize: function(width,height) {
		this.grid.width = this.canvas.width = width;
		this.grid.height = this.canvas.height = height;
		this.drawGrid(36);
	}
	,draw: function(frequency,waveform) {
		this.ctx.clearRect(0,0,this.canvas.width,this.canvas.height);
		var bw = this.canvas.width / waveform.length;
		var px = 0.0;
		this.ctx.strokeStyle = "rgb(90,90,90)";
		this.ctx.beginPath();
		var _g1 = 0;
		var _g = waveform.length;
		while(_g1 < _g) {
			var i = _g1++;
			var py = waveform[i] * this.canvas.height / 2 + this.canvas.height / 2;
			if(i == 0) {
				this.ctx.moveTo(px,py);
			} else {
				this.ctx.lineTo(px,py);
			}
			px += bw;
		}
		this.ctx.lineTo(this.canvas.width,this.canvas.height / 2);
		this.ctx.stroke();
		var copy = new Uint8Array(frequency.length);
		var _g11 = 0;
		var _g2 = frequency.length;
		while(_g11 < _g2) {
			var i1 = _g11++;
			copy[i1] = frequency[i1];
		}
		this.frequencyHistory.push(copy);
		if(this.frequencyHistory.length > 60) {
			this.frequencyHistory.shift();
		}
		var frequencyMax = new Uint8Array(frequency.length);
		var _g3 = 0;
		var _g12 = this.frequencyHistory;
		while(_g3 < _g12.length) {
			var freq = _g12[_g3];
			++_g3;
			var _g31 = 0;
			var _g21 = freq.length;
			while(_g31 < _g21) {
				var i2 = _g31++;
				var va = freq[i2];
				var vb = frequencyMax[i2];
				if(va > vb) {
					frequencyMax[i2] = va;
				}
			}
		}
		this.drawFrequency(frequencyMax,"rgba(40,40,40,0.8)");
		this.drawFrequency(frequency,"rgb(230,230,230)");
	}
	,drawFrequency: function(data,color) {
		var bw = this.canvas.width / data.length | 0;
		var bh;
		var px = 0.0;
		this.ctx.beginPath();
		this.ctx.fillStyle = color;
		var _g1 = 0;
		var _g = data.length;
		while(_g1 < _g) {
			var i = _g1++;
			bh = this.canvas.height * (data[i] / this.canvas.height);
			this.ctx.fillRect(i * (bw + 1),this.canvas.height - bh,bw,bh);
		}
	}
	,drawGrid: function(dd) {
		var ctx = this.grid.getContext("2d",null);
		ctx.lineWidth = 1;
		ctx.strokeStyle = "rgb(20,20,20)";
		var _g1 = 0;
		var _g = this.canvas.width / dd | 0;
		while(_g1 < _g) {
			var i = _g1++;
			var px = i * dd;
			ctx.moveTo(px,0);
			ctx.lineTo(px,this.canvas.height);
		}
		var _g11 = 0;
		var _g2 = this.canvas.height / dd | 0;
		while(_g11 < _g2) {
			var i1 = _g11++;
			var py = i1 * dd;
			ctx.moveTo(0,py);
			ctx.lineTo(this.canvas.width,py);
		}
		ctx.stroke();
	}
	,__class__: soda_Spectrum
};
String.prototype.__class__ = String;
String.__name__ = true;
Array.__name__ = true;
var Int = { __name__ : ["Int"]};
var Dynamic = { __name__ : ["Dynamic"]};
var Float = Number;
Float.__name__ = ["Float"];
var Bool = Boolean;
Bool.__ename__ = ["Bool"];
var Class = { __name__ : ["Class"]};
var Enum = { };
var ArrayBuffer = $global.ArrayBuffer || js_html_compat_ArrayBuffer;
if(ArrayBuffer.prototype.slice == null) {
	ArrayBuffer.prototype.slice = js_html_compat_ArrayBuffer.sliceImpl;
}
var Float32Array = $global.Float32Array || js_html_compat_Float32Array._new;
var Uint8Array = $global.Uint8Array || js_html_compat_Uint8Array._new;
js_Boot.__toStr = ({ }).toString;
js_html_compat_Float32Array.BYTES_PER_ELEMENT = 4;
js_html_compat_Uint8Array.BYTES_PER_ELEMENT = 1;
om_System.mobileUserAgents = ["Android","webOS","iPhone","iPad","iPod","BlackBerry","IEMobile","Opera Mini"];
soda_App.main();
})(typeof window != "undefined" ? window : typeof global != "undefined" ? global : typeof self != "undefined" ? self : this);

//# sourceMappingURL=soda.js.map